### ISSUE TITLE
Error: Can't call View#autorun from inside render()

### ISSUE THREAD

**Issue by maxnowack** [peerlibrary/meteor-computed-field#12]
I get the following exception in version v0.6.0
````
meteor.js?hash=e3f53db…:930 Exception in template helper: Error: Can't call View#autorun from inside render(); try calling it from the created or rendered callback
    at Blaze.View.autorun (http://localhost:3000/packages/blaze.js:1907:11)
    at autorun (http://localhost:3000/packages/peerlibrary_computed-field.js:52:28)
    at startAutorun (http://localhost:3000/packages/peerlibrary_computed-field.js:59:16)
    at new ComputedField (http://localhost:3000/packages/peerlibrary_computed-field.js:89:5)
````
before I updated, I was using v0.3.1 and it was working

**Comment by mitar** [comment]
Inside what are you using your computed field? So what is the context outside?

**Comment by maxnowack** [comment]
Yeah sorry, I'm working since 13 hours for now. I need to sleep.
I have have a little function that formats a date with the users date format. I'm using this function on server side and as a blaze helper. The function looks like the following:

``` es6
export default (date, options) => {
  const dateFormat = Meteor.isServer
    ? () => getDateFormat(options.userId, options.teamId)
    : new ComputedField(() => getDateFormat())
  return moment(date).format(_.isString(options) ? options : dateFormat())
}
```

I'm calling this blaze helper directly inside the template and as a normal function inside some react components. The error only occurs if I use the function as a blaze helper.

**Comment by mitar** [comment]
Hm, yes, inside template helpers computed field currently does not work well because of the last change.

As a workaround for now, you can do something like:

``` js
return Blaze._withCurrentView(null, () => {
  // your original code
});
```

This will trick computed field into not trying to use template level autorun.

Personally, I prefer attaching computed fields to template instances inside `onCreated` or `onRendered` and then simply access them inside template helpers. But I see that you cannot make this easily here because of the options.
