### ISSUE TITLE
readme is obscure

### ISSUE THREAD

**Issue by avalanche1** [peerlibrary/meteor-computed-field#7]
Readme is so obscure and complicated...
What's the purpose of this package? Can you provide typical use cases in readme?

**Comment by mitar** [comment]
Not sure how exactly. There is an example at the beginning? It is just an autorun + reactive variable put together.

Feel free to provide a better example.

**Comment by avalanche1** [comment]
I would if I understood what's the practical benefit of using this package.

**Comment by mitar** [comment]
Caching a result of reactive computation. Instead of computing every time, just so that you realize that nothing changed, you can cache it into a computed field. It will be recomputed only when dependencies really change. Otherwise you will get the cached value back.

In some way, memoization for reactive computations.

It can help you prevent recomputing too much when you use reactivity.

**Comment by avalanche1** [comment]
How do you use it in your projects? Did you measure performance impact?

**Comment by mitar** [comment]
What do you mean? I just see that things are not rerendered when there is no change in the value.

I use it with Blaze Components to attach fields to the component.

**Comment by avalanche1** [comment]
Without it your fields are like flashing or smth?

**Comment by mitar** [comment]
No, they are just recomputed unnecessary.

**Comment by avalanche1** [comment]
1
